# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "53ea1c4442865ad34fa59d488615897b"
name = "Multivariants"
handle = "multivariants-1"
application_url = "https://heritage-hung-sparc-reconstruction.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "myfastmart2.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://heritage-hung-sparc-reconstruction.trycloudflare.com/auth/callback",
  "https://heritage-hung-sparc-reconstruction.trycloudflare.com/auth/shopify/callback",
  "https://heritage-hung-sparc-reconstruction.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
